### ISSUE TITLE
Current To-Do's

### ISSUE THREAD

**Issue by petbrueck** [petbrueck/survey.tm#1]
Just as a place to compile main ToDo's for now: 

## TODO
- [ ]  Revise `batchTranslate_Deepl2()`: Issues caused if language sheets in GS are not named in ISO649 
- [ ] A main wrapper function?
- [ ] pkgdown.
- [ ] html-tag check: Have only those tags that are different added to comment ( not those counts that are identical). 
- [ ] html-tag check: check again with heavy formatting, e.g. '953faa24e13144ac984e1ad62593aab5'
- [ ] create_suso_file() - Assert that input is not null (especially source_questionnaire)
- [ ] Add a sheet in Template Sheet on translation instructions for both survey.tm users and Translators. Also stress that multiple sheets for separate language, but contain all the same (if no manual tweaks are done by user)
- [ ] `get_suso_tfiles`: print feedback to user
- [ ] Cleanup of function names & argument naming convention to make clear between translation and questionnaire
- [ ] Unit Tests
- [ ] Add a "status" parameter to Translation API functions
- [ ] Improve & add similarity score function
- [ ] TODOs in functions (: 
- [ ] If new questionnaire added for which text item exist, not reflected in "QUestionnaire(s)" cell (sticks with old questionnaire)
- [ ] Remove the value.unique in Google Sheet? 
- [ ] Color coding as dedicated function? Not really?  It is a one liner. Add to doc as an example?
- [ ] Confirm issue if special unicodes & readxl (e.g with "953faa24e13144ac984e1ad62593aab5")
- [ ] allow local qnr template file to be read instead of pulled? 
- [ ] ODK Stream
- [ ] move todos in seperate issues (:
